### ISSUE TITLE
Upgrade ant version

### ISSUE THREAD

**Issue by leewin12** [grails-plugins/grails-standalone#9]
Ant versions less tha 1.9 is incompatible with jdk1.8.
Do you have any plan to update ant version?

**Comment by krockode** [comment]
Checkout [Issue 18](https://jira.grails.org/browse/GPSTANDALONE-18) in jira.  Basically, this is fixed in grails 3.0.

**Comment by erichelgeson** [comment]
People will still be using 2.x for quite a while and it's not a trivial upgrade from 2->3. I did open a PR on 2.5.x but still an open question on it, unsure if anyone knows more about gant in grails: https://github.com/grails/grails-core/pull/627
